### ISSUE TITLE
Return code 0 on unsuccessfull upload

### ISSUE THREAD

**Issue by grisu48** [SUSE-Enceladus/ec2imgutils#93]
The `ec2uploadimg` tool terminates with exit code 0, also if there are obvious configuration issues and thereby no image being uploaded. See the following output we obtained from one of our openQA test runs, where we rely on the return code of `ec2uploadimg` to determine, if the upload was successful.

```
# ec2uploadimg ... 'SLES15-SP4.aarch64-0.9.9-EC2-Build1.55.raw.xz'
Creating temporary security group
Temporary Security Group Created sg-062f66b1f33abb2bb in vpc 
Successfully allowed incoming SSH port 22 for security group sg-062f66b1f33abb2bb in 
Specified subnet subnet-b44c72df not found
Traceback (most recent call last):
  File "/root/.venv_ec2uploadimg/lib/python3.6/site-packages/ec2imgutils/ec2uploadimg.py", line 193, in _check_subnet_exists
    self._connect().describe_subnets(SubnetIds=[self.vpc_subnet_id])
  File "/root/.venv_ec2uploadimg/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.venv_ec2uploadimg/lib/python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSubnetID.NotFound) when calling the DescribeSubnets operation: The subnet ID 'subnet-XXXXXXXX' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.venv_ec2uploadimg/bin/ec2uploadimg", line 670, in <module>
    ami = uploader.create_image_use_root_swap(args.source)
  File "/root/.venv_ec2uploadimg/lib/python3.6/site-packages/ec2imgutils/ec2uploadimg.py", line 1029, in create_image_use_root_swap
    target_root_volume = self._create_image_root_volume(source)
  File "/root/.venv_ec2uploadimg/lib/python3.6/site-packages/ec2imgutils/ec2uploadimg.py", line 332, in _create_image_root_volume
    self._check_subnet_exists()
  File "/root/.venv_ec2uploadimg/lib/python3.6/site-packages/ec2imgutils/ec2uploadimg.py", line 196, in _check_subnet_exists
    raise EC2UploadImgException(error_msg)
ec2imgutils.ec2imgutilsExceptions.EC2UploadImgException: Specified subnet subnet-XXXXXXXX not found
EC2UploadImgException: Specified subnet subnet-XXXXXXXX not found
Successfully deleted security group sg-062f66b1f33abb2bb
```

The issue is likely attributed to the `except` block [here](https://github.com/SUSE-Enceladus/ec2imgutils/blob/master/ec2uploadimg#L956). I will try to create a pull request with a solution suggestion.

**Comment by rjschwei** [comment]
@grisu48 please file a bug in the SUSE bugzilla to allow us to update the package in SLE.

**Comment by rjschwei** [comment]
That's fine, PR and bsc are independent, thanks for the PR.

**Comment by apozsuse** [comment]
Thanks for the PR!
